#include "AnimationEventLists.h"

/*
/* The lists here might not contain all relevant animation events, so extend as necessary
*/


// TODO: Is the "skip intermediate" set really needed?

const Set<String> AnimationEventLists::g_actionsStart = {
    {"moveStart"},
    {"bowAttackStart"},
    {"blockStart"},
    {"staggerStart"},
    {"staggerIdleStart"},
    {"shoutStart"},
    {"SwimStart"},
    {"SprintStart"}, // TODO: test sprint
    {"SneakStart"},
    {"torchEquip"},
    {"blockHitStart"},
    {"bleedOutStart"},
    {"blockAnticipateStart"},
    {"HorseEnter"},
    {"HorseEnterInstant"},
    {"HorseEnterSwim"},
    {"MountedSwimStart"},
    {"ChairLookDownEnterInstant"},
    {"RagdollInstant"},
    // Idle animations
    {"IdleAlchemyEnter"},
    {"IdleBarDrinkingStart"},
    {"IdleBedEnterInstant"},
    {"IdleBedEnterStart"},
    {"IdleBedLeftEnterInstant"},
    {"IdleBedLeftEnterStart"},
    {"IdleBedRightEnterInstant"},
    {"IdleBedRightEnterStart"},
    {"IdleBedRollFrontEnterInstant"},
    {"IdleBedRollFrontEnterStart"},
    {"IdleBedRollLeftEnterInstant"},
    {"IdleBedRollLeftEnterStart"},
    {"IdleBedRollRightEnterInstant"},
    {"IdleBedRollRightEnterStart"},
    {"IdleBeggar"},
    {"IdleBlacksmithForgeEnter"},
    {"IdleBlackSmithingEnterInstant"},
    {"IdleBlackSmithingEnterStart"},
    {"IdleBoundKneesStart"},
    {"IdleCarryBucketFillEnter"},
    {"IdleCarryBucketPourEnter"},
    {"IdleCartBenchEnter"},
    {"IdleCartBenchEnterInstant"},
    {"IdleChairCHILDEnterInstant"},
    {"IdleChairCHILDFrontEnter"},
    {"IdleChairCHILDLeftEnter"},
    {"IdleChairCHILDRightEnter"},
    {"IdleChairEnterInstant"},
    {"IdleChairEnterStart"},
    {"IdleChairEnterToSit"},
    {"IdleChairFrontEnter"},
    {"IdleChairLeftEnter"},
    {"IdleChairRightEnter"},
    {"IdleCombatShieldStart"},
    {"IdleCombatStart"},
    {"IdleCookingSpitEnter"},
    {"IdleCounterStart"},
    {"IdleDialogueAngryStart"},
    {"IdleDialogueExpressiveStart"},
    {"IdleDialogueHappyStart"},
    {"idleDrinkingStandingStart"},
    {"IdleDrumStart"},
    {"idleEatingStandingStart"},
    {"IdleEnchantingEnter"},
    {"IdleFluteStart"},
    {"IdleFurnitureStart"},
    {"IdleGetAttention"},
    {"IdleHammerTableEnter"},
    {"IdleHammerTableEnterInstant"},
    {"IdleHammerWallEnter"},
    {"IdleHammerWallEnterInstant"},
    {"IdleHideLEnter"},
    {"IdleHideREnter"},
    {"IdleJarlChairEnter"},
    {"IdleJarlChairEnterInstant"},
    {"IdleLadderEnter"},
    {"IdleLadderEnterInstant"},
    {"IdleLayDownEnter"},
    {"IdleLayDownEnterInstant"},
    {"IdleLeanTable"},
    {"IdleLeanTableEnter"},
    {"IdleLeanTableEnterInstant"},
    {"IdleLeftChairEnterStart"},
    {"IdleLeverPushStart"},
    {"idleLooseSweepingStart"},
    {"IdleLuteStart"},
    {"IdleMillLoadStart"},
    {"IdlePickaxeEnter"},
    {"IdlePickaxeEnterInstant"},
    {"IdlePickaxeFloorEnter"},
    {"IdlePickaxeTableEnter"},
    {"IdleReadElderScrollStart"},
    {"IdleRightChairEnterStart"},
    {"IdleSearchingChest"},
    {"IdleSearchingTable"},
    {"IdleSharpeningWheelStart"},
    {"IdleSitCrossLeggedEnter"},
    {"IdleSitCrossLeggedEnterInstant"},
    {"IdleSitLedge"},
    {"IdleSitLedge_Enter"},
    {"IdleSitLedgeEnter"},
    {"IdleSitLedgeEnterInstant"},
    {"IdleStoolEnter"},
    {"IdleStoolEnterInstant"},
    {"IdleTableDrinkAndMugEnter"},
    {"IdleTableDrinkEnter"},
    {"IdleTableEnter"},
    {"IdleTableEnterInstant"},
    {"IdleTableEnterPlayer"},
    {"IdleTableMugEnter"},
    {"IdleTablePassOutEnter"},
    {"IdleTanningEnter"},
    {"IdleWallLeanStart"},
    {"IdleWarmHands"},
    {"IdleWebEnterInstant"},
    {"IdleWoodChopStart"},
    {"IdleWoodPickUpEnter"},
    {"IdleWoodPickUpEnterInstant"},
};

const Set<String> AnimationEventLists::g_actionsExit = {
    {"IdleForceDefaultState"}, // Belongs here too
    {"BleedOutEarlyExit"},
    {"HorseExit"},
    {"IdleChairExitToStand"},
    {"IdleChairFrontExit"},
    {"idleChairLeftExit"},
    {"idleChairRightExit"},
    {"IdleBedExitToStand"},
    {"IdleCartPrisonerAExit"},
    {"IdleFurnitureExit"},
    {"IdleFurnitureExitSlow"},
    {"IdleLaydown_Exit"},
    {"IdleLayDown_Exit"},
    {"IdleLounge_Exit"},
    {"IdleRailLeanExit"},
    {"IdleSitLedge_Exit"},
    {"IdleStoolBackExit"},
    {"IdleTableBackExit"},
    {"IdleWebExit"},
    {"IdleChairExitStart"},
    {"IdleBedExitStart"},
    {"IdleBedLeftExitStart"},
    {"IdleBedRightExitStart"},
    {"IdleBedRollFrontExitStart"},
    {"IdleBedRollLeftExitStart"},
    {"IdleBedRollRightExitStart"},
    {"IdleChairCHILDFrontExit"},
    {"IdleChairCHILDLeftExit"},
    {"IdleChairCHILDRightExit"},
};

// Commented out because of potential conflicts with other animation mods and I'm not sure if this is needed
//const Set<String> AnimationEventLists::g_actionsSkipIntermediate = {
//    {"attackStart"},
//    {"moveStop"},
//    {"WeapEquip"},
//    {"SprintStart"},
//    {"SprintStop"},
//    //{"CyclicFreeze"},
//    //{"CyclicCrossBlend"},
//    {"IdleStop"},
//    {"IdleStopInstant"},
//    {"IdleHDLeft"},
//    {"IdleHDLeftAngry"},
//    {"IdleHDRight"},
//    {"IdleHDRightAngry"},
//    {"MotionDrivenIdle"},
//    {"torchUnequip"},
//};

const Set<String> AnimationEventLists::g_actionsIgnore = {
    // Animation events with empty names don't carry anything useful besides 
    // various animvars updates and state changes to the running animations.
    // Ignored because there is too many of them on each frame
    {""},
    {"TurnLeft"},
    {"TurnRight"},
    {"turnStop"},
    {"CyclicFreeze"},
    {"CyclicCrossBlend"},
    {"NPC_BumpedFromBack"},
    {"NPC_BumpedFromLeft"},
    {"NPC_BumpedFromRight"},
    {"NPC_BumpEnd"},
    {"NPC_BumpFromFront"},
    {"NPC_TurnLeft180"},
    {"NPC_TurnLeft90"},
    {"NPC_TurnRight180"},
    {"NPC_TurnRight90"},
    {"NPC_TurnToWalkLeft180"},
    {"NPC_TurnToWalkLeft90"},
    {"NPC_TurnToWalkRight180"},
    {"NPC_TurnToWalkRight90"},
    // Ignore jump animations
    {"JumpDirectionalStart"},
    {"JumpFall"},
    {"JumpFallDirectional"},
    {"JumpFastEnd"},
    {"JumpFastLeft"},
    {"JumpFastRight"},
    {"JumpForwardEnd"},
    {"JumpForwardStart"},
    {"JumpLand"},
    {"JumpLandDirectional"},
    {"JumpLandEnd"},
    {"JumpLandFailSafe"},
    {"JumpLandFast"},
    {"JumpLandSoft"},
    {"JumpSoftEnd"},
    {"JumpStandingStart"},
    // There's an elusive bug on the client where it would spam "Unequip"
    // and "combatStanceStop" a lot after changing cells
    {"Unequip"},
    {"combatStanceStop"},
    // Weapon drawing is handled separately
    {"WeapEquip"},
    {"WeapSoloEquip"},
    {"WeapForceEquip"},
};
