// Generated by Tools/fallout4/gen_fo4_offsets.py.
// Fallout4.exe SHA256: fdcef37ac1230af6d0b0050eb2142b139ef3a867b37b9211fb6edfcc646072f8
static constexpr uint32_t kImageTimestamp = 0x6a727fcc;
static constexpr uint32_t kImageSize = 0x425a000;
