#include <TiltedOnlinePCH.h>

#include <Offsets.h>

#include <BuildInfo.h>
#include <spdlog/spdlog.h>

namespace fo4
{
struct NamedRva
{
    const char* name;
    uint32_t rva;
};

// The sorted tables live in OffsetsData.h, generated by the local tooling and
// kept out of the repository. Without it every lookup misses.
#if __has_include(<OffsetsData.h>)
#include <OffsetsData.h>
static const NamedRva kEmpty[1] = {{"", 0}};
static const NamedRva* GetNamedTable(size_t& aCount) noexcept { return GetNamedTable(aCount); }
static const NamedRva* GetRttiTable(size_t& aCount) noexcept { return GetRttiTable(aCount); }
#else
static const NamedRva kEmpty[1] = {{"", 0}};
static const NamedRva* GetNamedTable(size_t& aCount) noexcept { aCount = 0; return kEmpty; }
static const NamedRva* GetRttiTable(size_t& aCount) noexcept { aCount = 0; return kEmpty; }
#endif

static const uint8_t* Base() noexcept
{
    return reinterpret_cast<const uint8_t*>(GetModuleHandleA(nullptr));
}

static const NamedRva* Find(const NamedRva* apTable, size_t aCount, std::string_view acName) noexcept
{
    size_t lo = 0, hi = aCount;
    while (lo < hi)
    {
        const size_t mid = (lo + hi) / 2;
        const int cmp = acName.compare(apTable[mid].name);
        if (cmp == 0)
            return &apTable[mid];
        if (cmp < 0)
            hi = mid;
        else
            lo = mid + 1;
    }
    return nullptr;
}

uint32_t Rva(std::string_view acName) noexcept
{
    size_t count = 0;
    const auto* pTable = GetNamedTable(count);
    if (const auto* pEntry = Find(pTable, count, acName))
        return pEntry->rva;
    return 0;
}

void* Address(std::string_view acName) noexcept
{
    const uint32_t rva = Rva(acName);
    return rva ? const_cast<uint8_t*>(Base() + rva) : nullptr;
}

bool HasRtti(std::string_view acTypeName) noexcept
{
    size_t count = 0;
    const auto* pTable = GetRttiTable(count);
    return Find(pTable, count, acTypeName) != nullptr;
}

const void* Rtti(std::string_view acTypeName) noexcept
{
    size_t count = 0;
    const auto* pTable = GetRttiTable(count);
    if (const auto* pEntry = Find(pTable, count, acTypeName))
        return Base() + pEntry->rva;
    return nullptr;
}
} // namespace fo4
