
target("Launcher")
    set_kind("shared")
    set_group("Client")
    add_includedirs(".",)
    add_headerfiles("*.h")
    add_files("*.cpp")
    add_deps(
        "UiProcess", 
        "Common",
        "Encoding",
        "TiltedReverse",
        "TiltedHooks",
        "TiltedScript",
        "TiltedUi")
    add_packages(
        "tiltedcore", 
        "hopscotch-map",
        "discord",
        "cef")