-- TODO (Force): please align into namespace
lib_dir = os.curdir()
directx_dir = lib_dir .. "/DXSDK"

before_build(function(target)
	import("modules.version")

	local branch, commit, timestamp = version()

	local versionString = string.format([[
#pragma once
// This file was autogenerated by modules.version
#define BUILD_BRANCH "%s"
#define BUILD_COMMIT "%s"
#define BUILD_TIMESTAMP "%s"
]], branch, commit, timestamp)
	local curVersion = try
	{
		function()
			return io.open("Code/common/BuildInfo.h", "r")
		end
	}
	if curVersion~=nil then
		local curVersionString = curVersion:read("*a")
		curVersion:close()
		if (curVersionString == versionString) then
			return
		end
	end
	io.writefile("Code/common/BuildInfo.h", versionString)
end)

add_requires(
    "tiltedcore",
    "spdlog",
    "discord",
    "imgui")

-- all libraries listed here are under frequent change, and are thus not quired via
-- the xmake package manager, we intend to change this in the future though.

if is_plat("windows") then
	includes("./TiltedUI")
	includes("./TiltedReverse")
	includes("./TiltedHooks")
end

includes("./TiltedScript")
includes("./TiltedConnect")