#include <Structs/AnimationGraphDescriptorManager.h>
#include <Structs/Fallout4/AnimationGraphDescriptor_SuperMutantRootBehavior.h>



AnimationGraphDescriptor_SuperMutantRootBehavior::AnimationGraphDescriptor_SuperMutantRootBehavior(
    AnimationGraphDescriptorManager& aManager)
{
    enum Variables
    {
        kiState = 0,
        kiState_SuperMutantDefault = 1,
        kbGraphDriven = 2,
        kiSyncIdleLocomotion = 3,
        kiSyncTurnState = 4,
        kbGraphDrivenRotation = 5,
        kLookAtAdditive = 6,
        kbAllowHeadTracking = 7,
        kcamerafromx = 8,
        kcamerafromy = 9,
        kcamerafromz = 10,
        kLookAtUseBoneGains = 11,
        kLookAtOffGain = 12,
        kLookAtOnGain = 13,
        kLookAtOnLeadIn = 14,
        kLookAtNeck_OffLeadIn = 15,
        kLookAtUseIndividualLimits = 16,
        kLookAtOutOfRange = 17,
        kLookAtLimitAngleThresholdDeg = 18,
        kbGraphWantsFootIK = 19,
        km_errorOutTranslation = 20,
        km_alignWithGroundRotation = 21,
        km_worldFromModelFeedbackGain = 22,
        kLookAtSpine2_Enabled = 23,
        kLookAtChest_Enabled = 24,
        kLookAtSpine2_LimitAngleDeg = 25,
        kLookAtSpine2_LimitAngleDegVer = 26,
        kbHeadTrackingDebug = 27,
        kLookAtChest_LimitAngleDegVer = 28,
        kLookAtChest_LimitAngleDeg = 29,
        kLookAtNeck_LimitAngleDeg = 30,
        kLookAtNeck_LimitangleDegVer = 31,
        kLookAtNeck_Enabled = 32,
        kLookAtHead_LimitAngleDeg = 33,
        kLookAtHead_LimitAngleDegVer = 34,
        kLookAtHead_Enabled = 35,
        kfTimeStep = 36,
        kfSpineTwistGainAdj = 37,
        kfSpineTwistGain = 38,
        kSpineXTwist = 39,
        kSpineYTwist = 40,
        kSpineZTwist = 41,
        kfHeadTwistGainAdj = 42,
        kfHeadTwistGain = 43,
        kHeadXTwist = 44,
        kHeadYTwist = 45,
        kHeadZTwist = 46,
        kbAnimationDriven = 47,
        kbIsSynced = 48,
        kiState_SuperMutantGun = 49,
        kiState_SuperMutantMelee = 50,
        kiState_SuperMutantScreenspace = 51,
        kiState_SuperMutantBlocking = 52,
        kiState_SuperMutantSighted = 53,
        kfHitReactionEndTimer = 54,
        kHeadTwistMinMax = 55,
        kSpineTwistMinMax = 56,
        kiAttackState = 57,
        kiGetUpType = 58,
        kfMaxForce = 59,
        kfRagdollAnimAmount = 60,
        kbHumanoidFootIKDisable = 61,
        kfik_footplantedgain = 62,
        kbEquipOk = 63,
        kDirection = 64,
        kSpeed = 65,
        kIsSprinting = 66,
        kiSyncSprintState = 67,
        kbFreezeSpeedUpdate = 68,
        kbInJumpState = 69,
        kbDoNotInterrupt = 70,
        kTurnDelta = 71,
        kbInLandingState = 72,
        kbEnableRoot_IsActiveMod = 73,
        kfRandomClipStartTimePercentage = 74,
        kiIsInSneak = 75,
        kWalkSpeedMult = 76,
        kJogSpeedMult = 77,
        krunSpeedMult = 78,
        kiSyncLocomotionSpeed = 79,
        kbAllowRotation = 80,
        kIsNPC = 81,
        kiControlsIdleSync = 82,
        kIsPlayer = 83,
        kbPathingInterruptibleIdle = 84,
        kbBlockPOVSwitch = 85,
        kiIsPlayer = 86,
        kSpeedSmoothed = 87,
        ktestBlend = 88,
        kLeftHandIKOn = 89,
        kbIsThrowing = 90,
        kiSyncWalkRun = 91,
        kfIdleStopTime = 92,
        kTurnDeltaSmoothed = 93,
        kiSyncJumpState = 94,
        kbTalkableWithItem = 95,
        kEnable_bEquipOK = 96,
        kiDynamicLoopStartState = 97,
        kfBodyMorphOffset = 98,
        kbIsInMT = 99,
        kbManualGraphChange = 100,
        kisMirrored = 101,
        kIsAttackReady = 102,
        kIsFirstPerson = 103,
        kAimPitchMax = 104,
        kbAimActive = 105,
        kAimHeadingCurrent = 106,
        kAimPitchCurrent = 107,
        kfStumbleTimerThreshold = 108,
        kfStumbleSpeedStopThreshold = 109,
        kfStumbleDir = 110,
        kfStumbleDirDeltaStopThreshold = 111,
        kcHitReactionDir = 112,
        kcHitReactionBodyPart = 113,
        kiState_Raider_Stumble_Rifle = 114,
        kisJumping = 115,
        kIsSneaking = 116,
        kbNotHeadTrack = 117,
        kisReloading = 118,
        kweaponSpeedMult = 119,
        kbIsSneaking = 120,
        kfVaultDistance = 121,
        kbDisableAttackReady = 122,
        kbSyncDirection = 123,
        kbActorMobilityNotFullyCrippled = 124,
        kbRootRifleEquipOk = 125,
        kbAnimateWeaponBones = 126,
        kfVaultHeight = 127,
        kGunGripPointer = 128,
        kbForceIdleStop = 129,
        kiSyncShuffleState = 130,
        kisSightedOver = 131,
        kAimHeadingMaxCCW = 132,
        kAimHeadingMaxCW = 133,
        kfDirectAtSavedGain = 134,
        kbPartialCover = 135,
        kiSyncSneakWalkRun = 136,
        kfLocomotionWalkPlaybackSpeed = 137,
        kfLocomotionJogPlaybackSpeed = 138,
        kfLocomotionRunPlaybackSpeed = 139,
        kAimPitchMaxUp = 140,
        kAimPitchMaxDown = 141,
        kRightHandIKOn = 142,
        kiSyncSightedState = 143,
        kiWeaponChargeMode = 144,
        kfSpeedWalk = 145,
        kbBlockPipboy = 146,
        kspeedDamped = 147,
        kDirectionSmoothed = 148,
        kLeftHandIKControlsModifierActive = 149,
        kReloadSpeedMult = 150,
        kiSyncReadyAlertRelaxed = 151,
        k_TestInt = 152,
        kfLeftHandIKFadeOut = 153,
        kfLeftHandIKTransformOnFraction = 154,
        kbUseLeftHandIKDefaults = 155,
        kiLocomotionSpeedState = 156,
        kfLocomotionSneakWalkPlaybackSpeed = 157,
        kfLocomotionSneakRunPlaybackSpeed = 158,
        kiSyncGunDown = 159,
        kiRifleDrawnStateID = 160,
        kbAimEnabled = 161,
        kbSupportedDeathAnim = 162,
        kbCCOnStairs = 163,
        kbCCSupport = 164,
        kbShuffleSighted2 = 165,
        kiSyncDirection = 166,
        kbShuffleSighted = 167,
        kbAimCaptureEnabled = 168,
        kbFreezeRotationUpdate = 169,
        kInt32Variable00 = 170,
        k_test = 171,
        k_Test2 = 172,
        kGunGripPointer_Mirrored = 173,
        kHandIKControlsDataActive = 174,
        kHandIKControlsDataActive_Mirrored = 175,
        kRifleDrawnCurrentState = 176,
        k_TestBool = 177,
        kCurrentJumpState = 178,
        kDirectionDegrees = 179,
        kiWantBlock = 180,
        kiState_NPCBlocking = 181,
        kiSyncForwardBackward = 182,
        kIsBlocking = 183,
        kiSyncForwardBackward00 = 184,
        kfPitchUpLimit = 185,
        kfPitchDownLimit = 186,
        kbDisableIsAttackReady = 187,
        kbUseRifleReadyDirectAt = 188,
        kiMeleeState = 189,
        kTEMPIsPlayer = 190,
        kiSyncRunDirection = 191,
        kbEquipOkIsActiveEnabled = 192,
        kbRenderFirstPersonInWorld = 193,
        kPose = 194,
        kbDisableSpineTracking = 195,
        kbAdjust1stPersonFOV = 196,
        kLookAtOutsideLimit = 197,
        kLookAtLimitAngleDeg = 198,
        kLookAtHead_OnGain = 199,
        kiTalkGenerator = 200,
        kiPcapTalkGenerator = 201,
        kbIsInFlavor = 202,
        kstaggerDirection = 203,
        kstaggerMagnitude = 204,
    };

    uint64_t key = 4192192227136413005;

    AnimationGraphDescriptorManager::Builder s_builder(aManager, key,
        AnimationGraphDescriptor(
            {
                kisReloading,
                kbAnimateWeaponBones,
                kbAimActive,
                kbCCSupport,
                kbUseLeftHandIKDefaults,
                kbIsInMT,
                kbBlockPipboy,
                kbAnimationDriven,
                kHandIKControlsDataActive_Mirrored,
                kLeftHandIKControlsModifierActive,
                kbEquipOk,
                kHandIKControlsDataActive,
                kLeftHandIKOn,
                kisMirrored,
                kbAllowHeadTracking,
                kbAimEnabled,
                kbAllowRotation,
                kbDisableAttackReady,
                kbPartialCover,
                kbManualGraphChange,
                kIsSneaking,
                kbIsSynced,
                kbIsThrowing,
                kIsAttackReady,
                kLookAtOutOfRange,
            },
            {
                kfSpineTwistGainAdj,
                kTurnDelta,
                kHeadYTwist,
                kfLocomotionRunPlaybackSpeed,
                kSpeedSmoothed,
                kfTimeStep,
                kHeadXTwist,
                kAimHeadingMaxCW,
                kSpineXTwist,
                kSpeed,
                kAimPitchCurrent,
                kfLeftHandIKTransformOnFraction,
                kAimHeadingMaxCCW,
                kDirection,
                kHeadZTwist,
                kAimHeadingCurrent,
                kfHitReactionEndTimer,
                kfik_footplantedgain,
                kSpineZTwist,
                kstaggerDirection,
                kfDirectAtSavedGain,
                kSpineYTwist,
                kfLocomotionWalkPlaybackSpeed,
                kDirectionDegrees,
                kTurnDeltaSmoothed,
                kstaggerMagnitude,
                kfLeftHandIKFadeOut,
                kfHeadTwistGainAdj,
            },
            {
                kiSyncIdleLocomotion,
                kcHitReactionBodyPart,
                kcHitReactionDir,
                kiSyncTurnState,
                kiSyncDirection,
                kiLocomotionSpeedState,
                kiSyncSightedState,
                kiSyncReadyAlertRelaxed,
                kRifleDrawnCurrentState,
                kiState,
            }));
}
