#include <Structs/AnimationGraphDescriptorManager.h>
#include <Structs/Fallout4/AnimationGraphDescriptor_Alien.h>


AnimationGraphDescriptor_Alien::AnimationGraphDescriptor_Alien(
    AnimationGraphDescriptorManager& aManager)
{
    enum Variables
    {
        kiState = 0,
        kiState_Alien = 1,
        kbGraphDriven = 2,
        kbGraphDrivenRotation = 3,
        kbGraphDrivenTranslation = 4,
        kbAnimationDriven = 5,
        kbAllowRotation = 6,
        kstaggerDirection = 7,
        kstaggerMagnitude = 8,
        kiGetUpType = 9,
        kiCombatState = 10,
        kbHeadTrackingEnabled = 11,
        kbGraphWantsHeadTracking = 12,
        kLookAtOutOfRange = 13,
        kcamerafromx = 14,
        kcamerafromy = 15,
        kcamerafromz = 16,
        kbHeadTrackingDebug = 17,
        kfTimeStep = 18,
        kfSpineTwistGainAdj = 19,
        kfSpineTwistGain = 20,
        kSpineXTwist = 21,
        kSpineYTwist = 22,
        kSpineZTwist = 23,
        kfHeadTwistGainAdj = 24,
        kfHeadTwistGain = 25,
        kHeadXTwist = 26,
        kHeadYTwist = 27,
        kHeadZTwist = 28,
        kbGraphWantsFootIK = 29,
        km_errorOutTranslation = 30,
        km_alignWithGroundRotation = 31,
        km_worldFromModelFeedbackGain = 32,
        kiSyncTurnState = 33,
        kiNonCombatStandingState = 34,
        kiNonCombatLocomotionState = 35,
        kiSyncIdleLocomotion = 36,
        kSpeed = 37,
        kiCombatStandingState = 38,
        kiCombatLocomotionState = 39,
        kIsAttackReady = 40,
        kbEnableAttackMod = 41,
        kbEquipOk = 42,
        kfRandomClipStartTimePercentage = 43,
        kbIsLaying = 44,
        kbIsGrazing = 45,
        kidleTimeMin = 46,
        kidleTimeMax = 47,
        kiDynamicAnimSelector = 48,
        kbIsSitting = 49,
        kDirection = 50,
        kiMovementSpeed = 51,
        kAimHeadingMaxCCW = 52,
        kAimHeadingMaxCW = 53,
        kfAimOnGain = 54,
        kfDirectAtHeadingSavedGain = 55,
        kbAimActive = 56,
        kAimHeadingCurrent = 57,
        kAimPitchUpMax = 58,
        kAimPitchDownMax = 59,
        kAimPitchCurrent = 60,
        kfDirectAtSavedGain = 61,
        kAimPitchMaxUp = 62,
        kAimPitchMaxDown = 63,
        kbAimEnabled = 64,
        kbAimCaptureEnabled = 65,
        kfWalkSpeed = 66,
        kfRunSpeed = 67,
        kbAllowHeadTracking = 68,
        kLookAtChest_Enabled = 69,
        kLookAtSpine2_Enabled = 70,
        kbFreezeSpeedUpdate = 71,
        kiIsInSneak = 72,
        kbRenderFirstPersonInWorld = 73,
        kbDisableSpineTracking = 74,
        kIsPlayer = 75,
        kbBlockPOVSwitch = 76,
        kbBlockPipboy = 77,
        kPose = 78,
        kbAdjust1stPersonFOV = 79,
        kiRecoilSelector = 80,
        kTurnDelta = 81,
        kIsBlocking = 82,
        kiSyncWalkRun = 83,
        kbManualGraphChange = 84,
        krecoilShortMult = 85,
        kLookAtOutsideLimit = 86,
        kbForceIdleStop = 87,
        kbDoNotInterrupt = 88,
        kLookAtLimitAngleDeg = 89,
        kLookAtChest_LimitAngleDeg = 90,
        kLookAtNeck_LimitAngleDeg = 91,
        kLookAtHead_LimitAngleDeg = 92,
        kLookAtHead_OnGain = 93,
        kLookAtAdditive = 94,
        kbEnableRoot_IsActiveMod = 95,
        kIsNPC = 96,
        kLookAtOnGain = 97,
        kLookAtOffGain = 98,
        kbTalkableWithItem = 99,
        kiTalkGenerator = 100,
        kbFreezeRotationUpdate = 101,
        kiPcapTalkGenerator = 102,
        kSpeedSmoothed = 103,
        kTurnDeltaSmoothed = 104,
        kbIsInFlavor = 105,
    };

    uint64_t key = 1050516629324185412;

    AnimationGraphDescriptorManager::Builder s_builder(aManager, key,
        AnimationGraphDescriptor(
            {
                kbAnimationDriven,
                kIsAttackReady,
                kLookAtOutOfRange,
                kbAimActive,
                kbAimEnabled,
                kbGraphWantsHeadTracking,
                kbEquipOk,
            },
            {
                kSpeed,
                kstaggerDirection,
                kfRunSpeed,
                kDirection,
                kHeadZTwist,
                kfHeadTwistGainAdj,
                kSpineZTwist,
                kfSpineTwistGainAdj,
                kfWalkSpeed,
                kfDirectAtSavedGain,
                kAimHeadingCurrent,
                kTurnDeltaSmoothed,
                kHeadYTwist,
                kSpeedSmoothed,
                kSpineYTwist,
                kfTimeStep,
                kAimPitchCurrent,
                kHeadXTwist,
                kSpineXTwist,
                kTurnDelta,
                kstaggerMagnitude,
            },
            {
                kiSyncTurnState,
                kiSyncIdleLocomotion,
                kiCombatState,
                kiMovementSpeed,
            }
        ));
}
