#include <Structs/AnimationGraphDescriptorManager.h>
#include <Structs/Fallout4/AnimationGraphDescriptor_Wolflike.h>



AnimationGraphDescriptor_Wolflike::AnimationGraphDescriptor_Wolflike(
    AnimationGraphDescriptorManager& aManager)
{
    enum Variables
    {
        kBone0Rotate = 0,
        kBone0Translate = 1,
        kBone1Translate = 2,
        kBone1Rotate = 3,
        kSpeed = 4,
        kiState_DogDefault = 5,
        kTrotMaxSpeed = 6,
        kTurnDelta = 7,
        kfWalkClipMult = 8,
        kfTrotClipMult = 9,
        kfRunClipMult = 10,
        kfWalkSpeed = 11,
        kfRunSpeed = 12,
        kfRoll = 13,
        kfRollMultiplier = 14,
        kbEquipOk = 15,
        kIsAttackReady = 16,
        kbAnimationDriven = 17,
        kbAllowRotation = 18,
        kfMaxTurnDelta = 19,
        kbIsMoving = 20,
        kLookAtOutOfRange = 21,
        kbGraphDriven = 22,
        kbGraphWantsHeadTracking = 23,
        kbForceIdleStop = 24,
        kbSitting = 25,
        kTurnDeltaDamped = 26,
        kbIsSynced = 27,
        kiSyncIdleLocomotion = 28,
        kcamerafromx = 29,
        kcamerafromy = 30,
        kcamerafromz = 31,
        kfHeadTrackingGainOn = 32,
        kfHeadTrackingGainOff = 33,
        kbHeadTrackingEnable = 34,
        kbGlobalSpineTwistEnable = 35,
        kfTrotFastClipMult = 36,
        kiSyncLocomotionRangeID = 37,
        kfSpringConstantZ = 38,
        km_worldFromModelFeedbackGain = 39,
        km_errorOutTranslation = 40,
        km_alignWithGroundRotation = 41,
        km_GainAlignWorldFromModel = 42,
        kfTimeStep = 43,
        kbGetTimeStepEnable = 44,
        kfTurnDeltaTarget = 45,
        kbUpdateSpineTwistTarget = 46,
        kbSupportedDeathAnim = 47,
        kfEarBlendTarget = 48,
        kfEarBlendDamped = 49,
        kfP = 50,
        kfI = 51,
        kfD = 52,
        kfMaxZRotRun = 53,
        kfMaxZRotWalk = 54,
        kfMaxTurnDeltaRun = 55,
        kfMaxTurnDeltaWalk = 56,
        kiFlavorIdleFilterIndex = 57,
        kbTickEnable = 58,
        kHeadTwistGainAdj = 59,
        kHeadTwistGain = 60,
        kHeadXTwist = 61,
        kHeadValueMinMax = 62,
        kHeadYTwist = 63,
        kHeadZTwist = 64,
        kfSpineTwistGainAdj = 65,
        kfSpineTwistGain = 66,
        kSpineXTwist = 67,
        kSpineValueMinMax = 68,
        kSpineYTwist = 69,
        kSpineZTwist = 70,
        kiState_DogSwim = 71,
        kiState = 72,
        kfHitReactionEndTimer = 73,
        kbReactsEnabled = 74,
        kfEarBlendDampedClamped = 75,
        kfHeadBlendTarget = 76,
        kfHeadBlendDamped = 77,
        kfBodyPartBlendTarget = 78,
        kfHeadBlendDampedClamped = 79,
        kfBodyPartBlendDamped = 80,
        kfBodyPartBlendDampedClamped = 81,
        kfEarBlendCombinedTarget = 82,
        kiGetUpType = 83,
        kfRagdollAnimAmount = 84,
        kfAnimDrivenFastEntryBlendTime = 85,
        kfAnimDrivenMediumExitBlendTime = 86,
        kfAnimDrivenEntryBlendTime = 87,
        kfAnimDrivenExitBlendTime = 88,
        kcHitReactionBodyPart = 89,
        kcHitReactionDir = 90,
        kiSyncCombatState = 91,
        kiRecoilSelection = 92,
        kfRollTarget = 93,
        kfMaxRollAccel = 94,
        kfAccelOrDecel = 95,
        kfSlowBlendingTransitionTime = 96,
        kiSyncHeadArchetype = 97,
        kiMaxTicksBodyFlavor = 98,
        kiMinTicksFlavor = 99,
        kiMaxTicksWalkFlavor = 100,
        kiMinTicksWalkFlavor = 101,
        kiMaxTicksWalk = 102,
        kiMinTicksWalk = 103,
        kbTailBlocked = 104,
        kiMaxTicksEar = 105,
        kiMinTicksEar = 106,
        kiMaxTicksEarFlavor = 107,
        kiMinTicksEarFlavor = 108,
        kiMaxTicksEye = 109,
        kiMinTicksEye = 110,
        kiMaxTicksTail = 111,
        kiMinTicksTail = 112,
        kiMaxTicksTailFlavor = 113,
        kiMinTicksTailFlavor = 114,
        kfSpeedSwimFast = 115,
        kfSpeedSwim = 116,
        kiSyncEyeBlink = 117,
        kiSyncEarLeft = 118,
        kiSyncEarLeftLoop = 119,
        kiSyncEarRight = 120,
        kiSyncEarRightLoop = 121,
        kiSyncEyeBlinkHalf = 122,
        kiSyncTailLoop = 123,
        kiSyncTail = 124,
        kiSyncSwimState = 125,
        kTurnDeltaSmoothed = 126,
        kBRollEnable = 127,
        kiSyncWalkPose = 128,
        kbWalkForwardRandomize = 129,
        kfChangeWalkPoseSecsMin = 130,
        kfChangeWalkPoseSecsMax = 131,
        kiSyncTurnState = 132,
        kbTailBusy = 133,
        kbFreezeRotationUpdate = 134,
        kbAllowHeadTracking = 135,
    };

    uint64_t key = 884686398289769216;

    AnimationGraphDescriptorManager::Builder s_builder(aManager, key,
        AnimationGraphDescriptor(
            {
                kbIsMoving,
                kIsAttackReady,
                kbGraphWantsHeadTracking,
                kbWalkForwardRandomize,
                kbSupportedDeathAnim,
                kLookAtOutOfRange,
                kcHitReactionDir,
                kbAnimationDriven,
                kbUpdateSpineTwistTarget,
                kcHitReactionBodyPart,
            },
            {
                kTurnDelta,
                kfBodyPartBlendDamped,
                kSpineXTwist,
                kfTurnDeltaTarget,
                kfHeadBlendDampedClamped,
                kTurnDeltaSmoothed,
                kfEarBlendDampedClamped,
                kfTrotFastClipMult,
                kSpineZTwist,
                kfEarBlendDamped,
                kHeadXTwist,
                kfAccelOrDecel,
                kfRunClipMult,
                kSpineYTwist,
                kfHeadBlendDamped,
                kfRoll,
                kfTrotClipMult,
                kfHitReactionEndTimer,
                kfTimeStep,
                kTurnDeltaDamped,
                kSpeed,
                kfBodyPartBlendDampedClamped,
                kfRollTarget,
                kfWalkClipMult,
                kHeadTwistGainAdj,
            },
            {
                kiSyncLocomotionRangeID,
                kiSyncIdleLocomotion,
                kiRecoilSelection,
                kiSyncCombatState,
                kiSyncTurnState,
                kiSyncWalkPose,
            }
        ));
}
