#include <Structs/AnimationGraphDescriptorManager.h>
#include <Structs/Fallout4/AnimationGraphDescriptor_YaoGuai.h>



AnimationGraphDescriptor_YaoGuai::AnimationGraphDescriptor_YaoGuai(
    AnimationGraphDescriptorManager& aManager)
{
    enum Variables
    {
        kiGetUpType = 0,
        kbAnimationDriven = 1,
        kiCombatState = 2,
        kfTimeStep = 3,
        kfSpineTwistGainAdj = 4,
        kfSpineTwistGain = 5,
        kSpineXTwist = 6,
        kSpineYTwist = 7,
        kSpineZTwist = 8,
        kcHitReactionBodyPart = 9,
        kiState = 10,
        kiState_YaoguaiDefault = 11,
        kbGraphDriven = 12,
        kbManualGraphChange = 13,
        kcamerafromx = 14,
        kcamerafromy = 15,
        kcamerafromz = 16,
        kbHeadTrackingOn = 17,
        kLookAtOutOfRange = 18,
        kbGraphWantsHeadTracking = 19,
        kfHeadTrackingGainOn = 20,
        kfHeadTrackingGainOff = 21,
        kbHeadTrackingEnabled = 22,
        kbHeadTrackingDebug = 23,
        kbSupportedDeathAnim = 24,
        kfTest = 25,
        kfHitReactionEndTimer = 26,
        kHeadTwistMinMax = 27,
        kiSyncTurnState = 28,
        kiNonCombatStandingState = 29,
        kiNonCombatLocomotionState = 30,
        kiSyncIdleLocomotion = 31,
        kSpeed = 32,
        kiCombatStandingState = 33,
        kiCombatLocomotionState = 34,
        kIsAttackReady = 35,
        kbEnableAttackMod = 36,
        kDirection = 37,
        kbEquipOk = 38,
        kfRandomClipStartTimePercentage = 39,
        kTurnDeltaSmoothed = 40,
        kbIsSynced = 41,
        kidleTimeMax = 42,
        kidleTimeMin = 43,
        kiSyncForwardState = 44,
        kiLocomotionSpeed = 45,
        kwalkBackSpeedMult = 46,
        kwalkForwardSpeedMult = 47,
        krunForwardSpeedMult = 48,
        kiDynamicAnimSelector = 49,
        kbAllowRotation = 50,
        kbAllowHeadTracking = 51,
        kLookAtChest_Enabled = 52,
        kLookAtSpine2_Enabled = 53,
        kbFreezeSpeedUpdate = 54,
        kiIsInSneak = 55,
        kbGraphWantsFootIK = 56,
        kbRenderFirstPersonInWorld = 57,
        kbDisableSpineTracking = 58,
        kIsPlayer = 59,
        kbBlockPOVSwitch = 60,
        kbBlockPipboy = 61,
        kPose = 62,
        kbAdjust1stPersonFOV = 63,
        kiRecoilSelector = 64,
        kstaggerDirection = 65,
        kstaggerMagnitude = 66,
        kTurnDelta = 67,
        kIsBlocking = 68,
        kiSyncWalkRun = 69,
        krecoilShortMult = 70,
        kLookAtOutsideLimit = 71,
        kbForceIdleStop = 72,
        kbDoNotInterrupt = 73,
        kLookAtLimitAngleDeg = 74,
        kLookAtChest_LimitAngleDeg = 75,
        kLookAtNeck_LimitAngleDeg = 76,
        kLookAtHead_LimitAngleDeg = 77,
        kLookAtHead_OnGain = 78,
        kLookAtAdditive = 79,
        kbEnableRoot_IsActiveMod = 80,
        kIsNPC = 81,
        kLookAtOnGain = 82,
        kLookAtOffGain = 83,
        kbTalkableWithItem = 84,
        kiTalkGenerator = 85,
        kbFreezeRotationUpdate = 86,
        kiPcapTalkGenerator = 87,
        kSpeedSmoothed = 88,
        kbIsInFlavor = 89,
    };

    uint64_t key = 837991345629064437;

    AnimationGraphDescriptorManager::Builder s_builder(aManager, key,
        AnimationGraphDescriptor(
            {
                kbGraphWantsHeadTracking,
                kbAnimationDriven,
                kIsAttackReady,
                kLookAtOutOfRange,
                kbEquipOk,
            },
            {
                kDirection,
                kSpineYTwist,
                kfTimeStep,
                kTurnDelta,
                kSpeedSmoothed,
                kSpineXTwist,
                kSpeed,
                kTurnDeltaSmoothed,
                krunForwardSpeedMult,
                kstaggerDirection,
                kwalkForwardSpeedMult,
                kfHitReactionEndTimer,
                kfSpineTwistGainAdj,
                kSpineZTwist,
            },
            {
                kiLocomotionSpeed,
                kiSyncTurnState,
                kiDynamicAnimSelector,
                kiCombatState,
                kiSyncIdleLocomotion,
                kcHitReactionBodyPart,
                kiRecoilSelector,
            }
        ));
}
