#include <Structs/AnimationGraphDescriptorManager.h>
#include <Structs/Skyrim/AnimationGraphDescriptor_SphereRoot_Behavior.h>

enum Variables
{
    kIsStaggering = 0,
    kstaggerMagnitude = 1,
    kcurrentDefaultState = 2,
    kiSyncTurnState = 3,
    kTurnDelta = 4,
    kiState = 5,
    kiState_SphereDefault = 6,
    kiSyncIdleLocomotion = 7,
    kDirection = 8,
    kSampledSpeed = 9,
    kbAnimationDriven = 10,
    kIsEquipping = 11,
    kIsUnequipping = 12,
    kiRightHandType = 13,
    kiState_SphereRanged = 14,
    kbWeapReady = 15,
    kIsAttackReady = 16,
    kIsAttacking = 17,
    kIsRecoiling = 18,
    kbIsSynced = 19,
    kspeed = 20,
    kIsFiringBow = 21,
    kSpeedStartVar = 22,
    kbEquipOk = 23,
    kiLeftHandType = 24,
    kIsBlocking = 25,
    kbAllowRotation = 26,
    kSpeedDamped = 27,
    kTurnDeltaDamped = 28,
    kTurnMin = 29,
    kiRightHandType_8bit = 30,
    kIntDirection = 31,
    kfMinSpeed = 32,
    kbAttached = 33,
    kIsBashing = 34,
    kstaggerDirection = 35,
    kiGetUpType = 36,
};

AnimationGraphDescriptor_SphereRoot_Behavior::AnimationGraphDescriptor_SphereRoot_Behavior(AnimationGraphDescriptorManager& aManager)
{
    AnimationGraphDescriptorManager::Builder s_builder(aManager, "SphereRoot_Behavior",
        AnimationGraphDescriptor(
        {kbEquipOk,
            kIsEquipping,
            kbWeapReady,
            kbAnimationDriven,
            kIsAttackReady,
            kbAllowRotation,
            kIsRecoiling,
            kIsStaggering,
            kIsAttacking,
            },
        {kspeed,
            kTurnDelta,
            kSampledSpeed,
            kDirection,
            },
        {kiSyncIdleLocomotion,
            kiSyncTurnState,
            kcurrentDefaultState,
            }));
}
