#!/usr/bin/env python3
"""Generate verified names and RTTI from CommonLibF4 IDs and the target PE."""

import argparse
import hashlib
import json
import re
import struct
from pathlib import Path

from pe import Image, load_library


def extract_ids(header):
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", header.read_text(), flags=re.S)
    tokens = re.finditer(r"namespace\s+([\w:]+)|inline\s+constexpr\s+REL::ID\s+(\w+)\s*\{\s*(\d+)\s*\}|[{}]", source)
    scopes = []
    pending = None
    result = {}
    for token in tokens:
        namespace, name, identifier = token.groups()
        if namespace:
            pending = namespace
        elif name:
            if int(identifier):
                context = "::".join(s for s in scopes if s)
                context = context.removeprefix("RE::ID").removeprefix("::")
                result[f"{context}::{name}" if context else name] = int(identifier)
        elif token.group() == "{":
            scopes.append(pending)
            pending = None
        elif token.group() == "}":
            scopes.pop()
    return result


def extract_rtti(image):
    result = {}
    for section in image.sections:
        name, rva, _, raw, size, flags = section
        if flags & 0x20000000:
            continue
        data = image.data[raw:raw + size]
        for match in re.finditer(rb"\.\?A[UV]([A-Za-z_][A-Za-z_0-9@]*)@@\x00", data):
            start = match.start() - 16
            if start < 0 or (rva + start) % 8:
                continue
            vtable, spare = struct.unpack_from("<QQ", data, start)
            if spare or image.section(vtable - 0x140000000) is None:
                continue
            type_name = match.group(1).decode()
            if type_name in result and result[type_name] != rva + start:
                raise ValueError(f"Duplicate RTTI descriptor: {type_name}")
            result[type_name] = rva + start
    return result


def generate(header, exe, library, output, tsv):
    image = Image(exe)
    ids = load_library(library, image)
    rows = {}
    for name, identifier in extract_ids(Path(header)).items():
        rva = ids.get(identifier, 0)
        if not rva:
            raise ValueError(f"Missing ID {identifier}: {name}")
        rows[name] = (identifier, rva)
    rtti = extract_rtti(image)
    digest = hashlib.sha256(image.data).hexdigest()
    lines = ["// Generated by Tools/fallout4/gen_fo4_offsets.py.",
             f"// Fallout4.exe SHA256: {digest}",
             f"static constexpr uint32_t kImageTimestamp = {image.timestamp:#x};",
             f"static constexpr uint32_t kImageSize = {image.size:#x};"]
    Path(output).write_text("\n".join(lines) + "\n")
    rtti_header = Path(output).parent / "RTTI.h"
    if rtti_header.exists():
        types = re.findall(r"extern template struct internal::RttiLocator<(\w+)>;", rtti_header.read_text())
        dynamic_cast = next(identifier for name, (identifier, _) in rows.items() if name.endswith("RTDynamicCast"))
        source = ["#include <TiltedOnlinePCH.h>", "", f"const VersionDbPtr<internal::TDynamicCast> internal::DynamicCast({dynamic_cast});", "",
                  "namespace internal", "{", "template <class T> RttiLocator<T>::RttiLocator(uint32_t aRva)", "{", "    m_rva = aRva;", "}", "",
                  "template <class T> const void* RttiLocator<T>::Get()", "{",
                  "    return m_rva ? reinterpret_cast<const uint8_t*>(GetModuleHandleW(nullptr)) + m_rva : nullptr;", "}", "} // namespace internal", ""]
        for type_name in types:
            source.append(f"template struct internal::RttiLocator<{type_name}>;")
            source.append(f"internal::RttiLocator<{type_name}> registerRtti_{type_name}({rtti.get(type_name, 0):#x});")
        (Path(output).parent / "RTTI.cpp").write_text("\n".join(source) + "\n")
    lines = [f"# Fallout4.exe SHA256: {digest}", "# kind\tid\trva\tname"]
    lines.extend(f"{'func' if image.executable(rva) else 'data'}\t{identifier}\t{rva:#x}\t{name}" for name, (identifier, rva) in sorted(rows.items()))
    lines.extend(f"rtti\t0\t{rva:#x}\t{name}" for name, rva in sorted(rtti.items()))
    Path(tsv).write_text("\n".join(lines) + "\n")
    print(f"Generated {len(rows)} verified IDs and {len(rtti)} RTTI descriptors")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("header", type=Path, help="CommonLibF4 include/RE/IDs.h")
    parser.add_argument("exe", type=Path)
    parser.add_argument("library", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("tsv", type=Path)
    args = parser.parse_args()
    generate(args.header, args.exe, args.library, args.output, args.tsv)


if __name__ == "__main__":
    main()
