name: Playable Skyrim Together Build

on:
  workflow_dispatch:
  schedule:
    # Every Friday at 1:00 p.m. UTC
    - cron: '0 13 * * 5'
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  prepare:
    if: ${{ github.repository_owner == 'tiltedphoques' || github.event_name != 'schedule' }} # Disable cron runs in forks
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          # We need full history in order to create a version string (BuildInfo.h)
          fetch-depth: 0

      - name: Store version in output
        id: version
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

  build-linux:
    needs: prepare
    uses: ./.github/workflows/linux.yml
    with:
      build-mode: 'release'
      upload-build-for-next-job: true

  build-windows:
    needs: prepare
    uses: ./.github/workflows/windows.yml
    with:
      build-mode: 'release'
      upload-build-for-next-job: true

  artifact-upload:
    runs-on: ubuntu-latest
    needs: [prepare, build-windows, build-linux]
    strategy:
      matrix:
        include:
          - platform: windows-x64
            filename: SkyrimTogether-Windows-x64
          - platform: DebugSymbols-x64
            filename: SkyrimTogether-DebugSymbols-x64
          - platform: linux-arm64
            filename: SkyrimTogether-Linux-server-arm64
          - platform: linux-amd64
            filename: SkyrimTogether-Linux-server-amd64

    steps:
      - name: Download artifact from the previous job
        uses: actions/download-artifact@v5
        with:
          name: internal-job-files-${{ matrix.platform }}-release
          path: output

      - name: Package into zip
        run: |
          zip -r "${{ matrix.filename }}_(${{ needs.prepare.outputs.version }}.zip" output

      - name: Re-upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyrim Together Build ${{ matrix.platform }} (${{ needs.prepare.outputs.version }})
          path: ${{ matrix.filename }}_(${{ needs.prepare.outputs.version }}.zip.zip

  release-upload:
    if: github.ref_type == 'tag'
    needs: [prepare, artifact-upload]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifact
        uses: actions/download-artifact@v5
        with:
          path: release-files
          pattern: Skyrim Together*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: Release ${{ needs.prepare.outputs.version }}
          files: release-files/**
          # Pre-release tag if push prerel
          prerelease: ${{ contains(github.ref, 'prerel') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
